version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:16.3.0
  ssh:
    docker:
      - image: arvindr226/alpine-ssh

commands:
  transfer:
    description: "Transfers deployment script via SCP"
    steps:
      - checkout
      - run:
          name: Transfer scripts
          command: scp -o StrictHostKeyChecking=no -r ./* $SSH_USER@$SSH_ADDRESS:/home/circleci/firstroom
          no_output_timeout: 30s
      - run:
          name: Run deployment
          command: ssh -o StrictHostKeyChecking=no -v $SSH_USER@$SSH_ADDRESS ./firstroom/deploy.sh

jobs:
  deploy:
    executor: ssh
    steps:
      - transfer

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main